version: '3.7'

services:

  app_one:
    image: app
    build: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  app_two:
    image: app
    build: app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  app_three:
    image: api
    build: api
    ports:
      - 8000:80
      - 8001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
  nginx:
    image: nginx
    container_name: nginx
    build: nginx
    ports:
      - 443:443
